#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-coercible
Version  : 1.0.0
Release  : 4
URL      : https://rubygems.org/downloads/coercible-1.0.0.gem
Source0  : https://rubygems.org/downloads/coercible-1.0.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# Coercible
[![Build Status](https://travis-ci.org/solnic/coercible.png?branch=master)](https://travis-ci.org/solnic/coercible)
[![Code Climate](https://codeclimate.com/github/solnic/coercible.png)](https://codeclimate.com/github/solnic/coercible)
[![Dependency Status](https://gemnasium.com/solnic/coercible.png)](https://gemnasium.com/solnic/coercible)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n coercible-1.0.0
gem spec %{SOURCE0} -l --ruby > rubygem-coercible.gemspec

%build
gem build rubygem-coercible.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
coercible-1.0.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/coercible-1.0.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/Changelog.md
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/Gemfile.devtools
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/Guardfile
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/coercible.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/config/flay.yml
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/config/flog.yml
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/config/mutant.yml
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/config/roodi.yml
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/config/site.reek
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/configurable.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/decimal.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/false_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/float.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/integer.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/time_coercions.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/coercer/true_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/configuration.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/coercible/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/support/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/lib/support/type_lookup.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/integration/configuring_coercers_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/shared/unit/coerced_predicate.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/shared/unit/configurable.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/array/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/array/to_set_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/class_methods/new_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/configurable/config_name_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/configurable/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date/to_date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date_time/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date_time/to_date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date_time/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date_time/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/date_time/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/decimal/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/decimal/to_decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/decimal/to_float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/decimal/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/decimal/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/element_reader_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/false_class/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/false_class/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/to_decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/to_float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/float/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/hash/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/hash/to_date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/hash/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/hash/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/datetime_format_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/datetime_proc_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/numeric/to_decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/numeric/to_float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/numeric/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/numeric/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/inspect_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/method_missing_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/to_array_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/to_hash_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/object/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/class_methods/config_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_boolean_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_constant_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_decimal_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_float_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_symbol_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/symbol/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/symbol/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time/to_integer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time_coercions/to_date_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time_coercions/to_datetime_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time_coercions/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/time_coercions/to_time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/true_class/coerced_predicate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/coercer/true_class/to_string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/coercible-1.0.0/spec/unit/coercible/configuration/class_methods/build_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/coercible-1.0.0.gemspec
